### ISSUE TITLE
Virtual Apps Bug

### ISSUE THREAD

**Issue by AkoposiNobi** [LightningMods/Itemzflow#46] opened 2024-06-29 14:16 UTC
I've found some of the bugs on the experimental features FG Games whenever you mount a game via the "Scan for Apps" button, and manually select the game on the ItemzFlow, icons are not loaded on the PS4 Home Menu but VIA "Change App Path" the icon appears on the menu.

As well as, *FG* Shortcuts on the PS4 Home Menu gives you an error CE-37695-0 or "cannot use content" when you eject and reinsert the USB that contains the game or at least restart your PS4. If you tried to relaunch the games inside the ItemzFlow, the app will spit out error code: 0x80e90004, unable to mount CUSA*****, DAEMON_SAID_NO, and Game dir has failed to change if you change the app path.

Finally, thank you for this awesome manager!

**Comment by AkoposiNobi** [comment] 2024-06-29 14:21
Here are the logs

[daemon.log](https://github.com/user-attachments/files/16040794/daemon.log)
[itemzflow_app.log](https://github.com/user-attachments/files/16040795/itemzflow_app.log)

**Comment by LightningMods** [comment] 2024-06-29 16:26
Hello, I'll take a look but do keep in mind that bugs are expected with this new experimental feature

**Comment by AkoposiNobi** [comment] 2024-06-29 16:44
Thank you for the reply! I'm well aware that this is an experimental feature, a near perfect feature but bugs are bugs 😂. If you need anything lemme know I'll try to help.

**Comment by LightningMods** [comment] 2024-06-29 20:07
Hello, I have uploaded a test PKG that should hopefully fix the icons not showing up when done through "Scan for apps", if not just upload the logs via the itemzflow settings menu, as for the other things reported, by design you will get an error after ejecting the USB and trying to use a Virtual app from the USB normally when you disconnect the USB you are supposed restart itemzflow as itemzflow remounts all the games every time its launched, the same goes for the "cannot use content" error after rebooting as you have to launch itemzflow for it to remount the virtual apps, the reason they are still on the home menu is because they are shortcuts but those shortcuts dont lead to anything without itemzflow, as for the "unable to mount CUSA*****, DAEMON_SAID_NO" error I have added a fix that (I hope) fixes that issue as well in the same test PKG

Test PKG: https://drive.google.com/file/d/1ZtjmVG2ezrcwcs3O42m-VHS9RqPQqdNv/view?usp=sharing

**Comment by AkoposiNobi** [comment] 2024-06-30 00:34
Hello again! I've test the PKG, the "Change App Path" now doesn't display an icon on the PS4 home menu at first but when I tried "Scan for apps" the icons finally shows on the ItemzFlow as well at the PS4 Home Menu. So I think it is somehow fixed now but broke something in the process.

I've remount my flash drive and restarted the ItemzFlow upon loading the app and it still says "unable to mount CUSA*****" and the shortcuts are again spitting those errors. I'll upload a test video that hopefully explains the things I have found out. 

Here are the test video and the logs: 
https://drive.google.com/file/d/1IhEdhKXwhZju5hi6S8cPD86ktjgb_v3f/view?usp=sharing
[itemzflow_app.log](https://github.com/user-attachments/files/16042650/itemzflow_app.log)
[daemon.log](https://github.com/user-attachments/files/16042651/daemon.log)

**Comment by LightningMods** [comment] 2024-06-30 01:10
try this PKG, it should at least fix the first issue
https://drive.google.com/file/d/1yQwxF5FB0ydvW9RrohF17Z-Qc5ZH8YuW/view?usp=sharing

**Comment by AkoposiNobi** [comment] 2024-06-30 03:41
Sweet! It seems like you've fixed the icons issue as well as the remounting issue. Thank you very much LM!

**Comment by AkoposiNobi** [comment] 2024-06-30 04:05
Here's the new test video and some logs if you need it:

https://drive.google.com/file/d/1IhEdhKXwhZju5hi6S8cPD86ktjgb_v3f/view?usp=drive_link 
[daemon.log](https://github.com/user-attachments/files/16043083/daemon.log)
[itemzflow_app.log](https://github.com/user-attachments/files/16043084/itemzflow_app.log)

THANK YOU VERY MUCH!

**Comment by ccfman2004** [comment] 2024-06-30 05:38
I have found a visual bug relating to this feature.  If you enter the FG Games and then back out and go to a regular app without closing Itemzflow, the Retail Game Updates and Trainers button icons are replaced with Override Title ID and Scan for Apps icons.  Fully closing Itemzflow files the issue until you enter FG Games and blackout again. The functionality of the Retail Game Updates and Trainers button do work properly just the icon is wrong.

![Itemzflow Game Manager_20240630010705](https://github.com/LightningMods/Itemzflow/assets/79392/8fe2d51b-6a10-4e59-9eaf-c8343d9777ec)
![Itemzflow Game Manager_20240630010718](https://github.com/LightningMods/Itemzflow/assets/79392/e28ad9e8-4943-401b-bcad-47fcc6039b1e)
![Itemzflow Game Manager_20240630010727](https://github.com/LightningMods/Itemzflow/assets/79392/7989b8cd-7800-4e35-b07c-1633a5dc6d39)

**Comment by LightningMods** [comment] 2024-06-30 18:56
@ccfman2004 this should fix that issue, hopefully the last VAPP issue for now
https://drive.google.com/file/d/1Dl7kZIt_9HUFnCFDXxXotQIurZXlRD9r/view?usp=sharing

**Comment by ccfman2004** [comment] 2024-06-30 19:10
That fixes my issue. Thanks.

**Comment by LightningMods** [comment] 2024-07-01 18:22
Hello, as per my tweet I have re-uploaded itemzflow 1.06 with all these fixes to the HB Store
https://x.com/LightningMods_/status/1807841651152539956

this is issue is now closed, if there are any other vapp issues in the future open another issue

**Closed by LightningMods** 2024-07-01 18:22 UTC
Labels: bug

**Comment by Cybereu** [comment] 2024-07-08 21:49
Does this feature works on PS5 for PS4 games ? 
I would like link my ps4 games(1000) to a external hd.
